<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.js"></script>
<script src="_zf/js/libs/vtortola.ng-terminal.js"></script>
<script src="_zf/application/views/scripts/terminal/example.js"></script>

<link rel="stylesheet" type="text/css" href="_zf/css/vtortola.ng-terminal.css">

<script src="_zf/application/views/scripts/terminal/example.command.filesystem.js"></script>
<script src="_zf/application/views/scripts/terminal/example.command.implementations.js"></script>
<script src="_zf/application/views/scripts/terminal/example.command.tools.js"></script>

<div ng-app='ng-terminal-example'>
	<div ng-controller="console">
	    <terminal> </terminal>
	</div>
</div>